# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VwzJBYfmNdxl7ZEpfqHXp-ilnyi9FTfM
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

from google.colab import files
uploaded = files.upload()
import io
data = pd.read_csv(io.BytesIO(uploaded['fake_or_real_news.csv']))

from google.colab import files
uploaded = files.upload()
import io
data = pd.read_csv(io.BytesIO(uploaded['fake_or_real_news.csv']))

print (3)

data['fake'] = data['label'].apply(lambda x: 0 if x == "REAL" else 1)

data = data.drop("label", axis=1)

data = data.drop("label", axis=1)

X, y = data['text'], data['fake']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

len(X_test)

vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

clf = LinearSVC()
clf.fit(X_train_vectorized, y_train)

clf.score(X_test_vectorized, y_test)

X_test.iloc[20]

with open("mytext.txt", "w", encoding= "utf-8") as f:
  f.write(X_test.iloc[20])

with open("mytext.txt", "r", encoding= "utf-8") as f:
  text = f.read()

vectorized_text = vectorizer.transform([text])

clf.predict(vectorized_text)

y_test.iloc[20]

print (0)